# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calligrapher_model1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1085, 706)
        Form.setMinimumSize(QtCore.QSize(1085, 706))
        Form.setMaximumSize(QtCore.QSize(1085, 706))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 10, 771, 691))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-21, -1, 791, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_input_button = QtWidgets.QPushButton(Form)
        self.start_input_button.setGeometry(QtCore.QRect(850, 30, 171, 51))
        self.start_input_button.setObjectName("start_input_button")
        self.truncate_board_button = QtWidgets.QPushButton(Form)
        self.truncate_board_button.setGeometry(QtCore.QRect(850, 110, 171, 51))
        self.truncate_board_button.setObjectName("truncate_board_button")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(850, 360, 171, 51))
        self.save_button.setObjectName("save_button")
        self.delete_first_trail_button = QtWidgets.QPushButton(Form)
        self.delete_first_trail_button.setGeometry(QtCore.QRect(850, 190, 171, 51))
        self.delete_first_trail_button.setObjectName("delete_first_trail_button")
        self.delete_last_trail_button = QtWidgets.QPushButton(Form)
        self.delete_last_trail_button.setGeometry(QtCore.QRect(850, 270, 171, 51))
        self.delete_last_trail_button.setObjectName("delete_last_trail_button")
        self.return_index_button = QtWidgets.QPushButton(Form)
        self.return_index_button.setGeometry(QtCore.QRect(850, 450, 171, 51))
        self.return_index_button.setObjectName("return_index_button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(820, 550, 61, 31))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(920, 560, 111, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(820, 590, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(820, 630, 91, 31))
        self.label_3.setObjectName("label_3")
        self.eraser_checkBox = QtWidgets.QCheckBox(Form)
        self.eraser_checkBox.setGeometry(QtCore.QRect(900, 520, 71, 17))
        self.eraser_checkBox.setObjectName("eraser_checkBox")
        self.press_color_change_frame = QtWidgets.QFrame(Form)
        self.press_color_change_frame.setGeometry(QtCore.QRect(920, 600, 71, 21))
        self.press_color_change_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.press_color_change_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.press_color_change_frame.setObjectName("press_color_change_frame")
        self.press_color_change_button = QtWidgets.QPushButton(Form)
        self.press_color_change_button.setGeometry(QtCore.QRect(990, 600, 51, 23))
        self.press_color_change_button.setObjectName("press_color_change_button")
        self.loose_color_change_button = QtWidgets.QPushButton(Form)
        self.loose_color_change_button.setGeometry(QtCore.QRect(990, 640, 51, 23))
        self.loose_color_change_button.setObjectName("loose_color_change_button")
        self.loose_color_change_frame = QtWidgets.QFrame(Form)
        self.loose_color_change_frame.setGeometry(QtCore.QRect(920, 640, 71, 21))
        self.loose_color_change_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loose_color_change_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loose_color_change_frame.setObjectName("loose_color_change_frame")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_input_button.setText(_translate("Form", "开始输入"))
        self.truncate_board_button.setText(_translate("Form", "清空画板"))
        self.save_button.setText(_translate("Form", "保存作品"))
        self.delete_first_trail_button.setText(_translate("Form", "去除首痕"))
        self.delete_last_trail_button.setText(_translate("Form", "去除尾痕"))
        self.return_index_button.setText(_translate("Form", "返回首页"))
        self.label.setText(_translate("Form", "画笔粗细"))
        self.label_2.setText(_translate("Form", "按住画笔颜色"))
        self.label_3.setText(_translate("Form", "松开画笔颜色"))
        self.eraser_checkBox.setText(_translate("Form", "橡皮擦"))
        self.press_color_change_button.setText(_translate("Form", "更改"))
        self.loose_color_change_button.setText(_translate("Form", "更改"))
