# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_model1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1085, 706)
        Form.setMinimumSize(QtCore.QSize(1085, 706))
        Form.setMaximumSize(QtCore.QSize(1085, 706))
        self.load_model_button = QtWidgets.QPushButton(Form)
        self.load_model_button.setGeometry(QtCore.QRect(840, 90, 171, 51))
        self.load_model_button.setObjectName("load_model_button")
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setGeometry(QtCore.QRect(840, 250, 171, 51))
        self.save_button.setObjectName("save_button")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 771, 691))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(80, 60, 20, 531))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(650, 60, 20, 531))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(90, 580, 571, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(90, 60, 571, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(810, 30, 231, 22))
        self.comboBox.setObjectName("comboBox")
        self.reset_button = QtWidgets.QPushButton(Form)
        self.reset_button.setGeometry(QtCore.QRect(840, 170, 171, 51))
        self.reset_button.setObjectName("reset_button")
        self.return_index_button = QtWidgets.QPushButton(Form)
        self.return_index_button.setGeometry(QtCore.QRect(840, 330, 171, 51))
        self.return_index_button.setObjectName("return_index_button")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(800, 470, 251, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.return_index_button_2 = QtWidgets.QPushButton(Form)
        self.return_index_button_2.setGeometry(QtCore.QRect(840, 510, 171, 51))
        self.return_index_button_2.setObjectName("return_index_button_2")
        self.return_index_button_3 = QtWidgets.QPushButton(Form)
        self.return_index_button_3.setGeometry(QtCore.QRect(840, 590, 171, 51))
        self.return_index_button_3.setObjectName("return_index_button_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_model_button.setText(_translate("Form", "载入模型"))
        self.save_button.setText(_translate("Form", "保存作品"))
        self.reset_button.setText(_translate("Form", "重置打点"))
        self.return_index_button.setText(_translate("Form", "返回首页"))
        self.return_index_button_2.setText(_translate("Form", "添加打点"))
        self.return_index_button_3.setText(_translate("Form", "删除打点"))
