# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMessageBox

class Ui_Form(QWidget):

    def __init__(self, Parent=None):
        super().__init__(Parent)
        self.setMouseTracking(True)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1085, 706)
        Form.setMinimumSize(QtCore.QSize(1085, 706))
        Form.setMaximumSize(QtCore.QSize(1085, 706))
        font = QtGui.QFont()
        font.setItalic(False)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        Form.setStyleSheet("")
        self.welcome_label = QtWidgets.QLabel(Form)
        self.welcome_label.setGeometry(QtCore.QRect(280, 70, 511, 151))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.calligrapher_button = QtWidgets.QPushButton(Form)
        self.calligrapher_button.setGeometry(QtCore.QRect(170, 300, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(False)
        self.calligrapher_button.setFont(font)
        self.calligrapher_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.calligrapher_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.calligrapher_button.setAcceptDrops(False)
        self.calligrapher_button.setToolTip("")
        self.calligrapher_button.setObjectName("calligrapher_button")
        self.editor_button = QtWidgets.QPushButton(Form)
        self.editor_button.setGeometry(QtCore.QRect(440, 300, 201, 61))
        self.editor_button.setObjectName("editor_button")
        self.practise_button = QtWidgets.QPushButton(Form)
        self.practise_button.setGeometry(QtCore.QRect(710, 300, 201, 61))
        self.practise_button.setObjectName("practise_button")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(850, 610, 201, 61))
        self.exit_button.setObjectName("exit_button")

        self.prompt_comboBox = QtWidgets.QComboBox(Form)
        self.prompt_comboBox.setGeometry(QtCore.QRect(425, 400, 231, 22))
        self.prompt_comboBox.setObjectName("prompt_comboBox")
        self.prompt_comboBox.addItem("")
        self.prompt_comboBox.addItem("")
        self.prompt_comboBox.addItem("")
        self.prompt_comboBox.addItem("")
        self.prompt_comboBox.addItem("")

        self.change_prompt_button = QtWidgets.QPushButton(Form)
        self.change_prompt_button.setGeometry(QtCore.QRect(455, 470, 171, 51))
        self.change_prompt_button.setObjectName("change_prompt_button")
        self.change_prompt_button.clicked.connect(self.show_change_result)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.welcome_label.setText(_translate("Form", "欢迎使用书法进阶软件"))
        self.calligrapher_button.setText(_translate("Form", "书法家模式"))
        self.editor_button.setText(_translate("Form", "编辑模式"))
        self.practise_button.setText(_translate("Form", "练习模式"))
        self.exit_button.setText(_translate("Form", "退出软件"))
        self.change_prompt_button.setText(_translate("Form", "画板提示框比例设置"))
        self.prompt_comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.prompt_comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.prompt_comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.prompt_comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.prompt_comboBox.setItemText(4, _translate("MainWindow", "5"))

    def change_prompt(self):
        self.prompt_value = self.prompt_comboBox.currentText()

    def show_change_result(self):
        self.change_prompt()
        QMessageBox.information(self, '设置成功', '设置三种模式画板提示框大小成功！')
